# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "./"

  # Default build command.
  command = "yarn dev-build"
